environment:
  ANACONDA_API_TOKEN:
    secure: DWpOnNw7bNyTmC2oXttZM3ovxggFrV3eMeuQJYcgync8g0tqwMmYEu84cFapIRqP
  CONDA_HOME: "C:\\Miniconda3"
  CONDA_PATH: "%CONDA_HOME%\\Scripts\\conda.exe"
    
install:
  # Install Miniconda.
  - powershell .\\.ci\\install.ps1
  # Configure conda.
  - |
    "%CONDA_PATH%" config --prepend channels conda-forge
    "%CONDA_PATH%" config --append channels ConorIA

build: false

test_script:
  - "%CONDA_PATH%" build -q .

on_success:
  - python .ci\move-conda-package.py
  - python .ci\anaconda-upload.py
