environment:
  ANACONDA_API_TOKEN:
    secure: DWpOnNw7bNyTmC2oXttZM3ovxggFrV3eMeuQJYcgync8g0tqwMmYEu84cFapIRqP
    
install:
  # Remove cygwin because the conda-forge folks do it
  - cmd: rmdir C:\cygwin /s /q
  # Configure conda.
  - cmd: |
      call C:\Miniconda3-x64\Scripts\activate.bat
      conda.exe config --prepend channels conda-forge
      conda.exe config --append channels ConorIA
      conda.exe update -yq conda
      conda.exe install -yq conda-build jinja2 anaconda-client

build: false

test_script:
  - cmd: |
      call C:\Miniconda3-x64\Scripts\activate.bat
      conda.exe build -q -m %cd%\.ci\variants.yaml .

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_success:
  - cmd: python %cd%\.ci\move-conda-package.py
  - cmd: python %cd%\.ci\anaconda-upload.py
