{% set version = '0.0.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-canadahcdx
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://gitlab.com/ConorIA/canadaHCDx.git
  git_tag: master

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base {{ r_base }}
    - r-canadaHCD
    - r-curl
    - r-dplyr
    - r-geosphere
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-storr
    - r-tibble
    - r-zoo

  run:
    - r-base {{ r_base }}
    - r-canadaHCD
    - r-curl
    - r-dplyr
    - r-geosphere
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-storr
    - r-tibble
    - r-zoo

test:
  commands:
    - $R -e "library('canadaHCDx')"           # [not win]
    - "\"%R%\" -e \"library('canadaHCDx')\""  # [win]

about:
  home: https://gitlab.com/ConorIA/canadaHCDx
  license: GPL-3
  summary: A number of functions to extend the useful canadaHCD package
    by Gavin L. Simposon (2016).
  license_family: GPL3

extra:
  recipie-maintainers:
    - ConorIA
