{% set version = '0.6.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-senamhir
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://gitlab.com/ConorIA/senamhiR.git
  git_tag: master

build:
  number: 0
  skip: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-dbi
    - r-dplyr
    - r-geosphere
    - r-leaflet
    - r-rmysql
    - r-tibble
    - r-zoo

  run:
    - r-base {{ r_base }}
    - r-dbi
    - r-dplyr
    - r-geosphere
    - r-leaflet
    - r-rmysql
    - r-tibble
    - r-zoo

test:
  commands:
    - $R -e "library('senamhiR')"  # [not win]

about:
  home: https://gitlab.com/ConorIA/senamhiR
  license: GPL-3
  summary: A collection of functions to obtain archived Peruvian climatological
    or hydrological data form the Peruvian National Meterology and Hydrology
    Service.
  license_family: GPL3

extra:
  recipie-maintainers:
    - ConorIA
