version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run: conda update -yq conda
      - run: conda config --prepend channels conda-forge
      - run: conda config --append channels ConorIA
      - run: conda install -yq conda-build
      - run: conda build -q -m .ci/variants.yaml .
      - persist_to_workspace:
          root: /opt/conda/conda-bld/
          paths:
            - "*/*.tar.bz2"
  upload:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run: conda install -yq anaconda-client
      - attach_workspace:
          at: pkgs
      - run: anaconda upload --summary "Uploaded by CircleCI" pkgs/*/*.tar.bz2 --force

workflows:
  version: 2
  run_all:
    jobs:
      - build
      - upload:
          requires:
            - build
