version: 2.1

jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run: >
          COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1) &&
          for file in $(ls .); do 
            if $(echo $COMMIT_MESSAGE | grep -Eq "${file}\s"); then
              folder=${file};
            fi; done && if [ "$folder" = "" ]; then folder="."; fi &&
          echo $folder > .folder
      - run: apt-get update -qq && apt-get -yqq install binutils #FIXME
      - run: conda config --prepend channels conda-forge
      - run: conda config --append channels ConorIA
      - run: conda install -yq conda conda-build
      - run: conda build -q -m $PWD/.ci/variants.yaml $(cat .folder)
      - persist_to_workspace:
          root: /opt/conda/conda-bld/
          paths:
            - "*/*.tar.bz2"
  upload:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run: conda install -yq anaconda-client
      - attach_workspace:
          at: pkgs
      - run: anaconda -t $CONDA_UPLOAD_TOKEN upload --summary "Uploaded by CircleCI" pkgs/*/*.tar.bz2 --force

workflows:
  version: 2
  run_all:
    jobs:
      - build
      - upload:
          requires:
            - build
