{% set version = "2.1.0" %}

package:
  name: ec3
  version: {{ version }}

source:
  git_url: https://github.com/ConorIA/ec3.py.git
  git_tag: conda

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - docopt
    - geopy
    - pandas
    - tqdm
  run:
    - python
    - docopt
    - geopy
    - pandas
    - tqdm

test:
  imports:
    - ec3

about:
  home: https://gitlab.com/ConorIA/ec3.py
  license: GPL-3
  summary: Access climate data from Government of Canada's Historical
    Climate Data API.
  license_family: GPL3
    
extra:
  recipe-maintainers:
    - ConorIA
