{% set version = '0.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-canadahcd
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/gavinsimpson/canadaHCD.git
  git_tag: master

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base {{ r_base }}
    - r-readr
    - r-tibble
    - r-curl
    - r-dplyr
    - r-zoo

  run:
    - r-base {{ r_base }}
    - r-readr
    - r-tibble
    - r-curl
    - r-dplyr
    - r-zoo

test:
  commands:
    - $R -e "library('canadaHCD')"           # [not win]
    - "\"%R%\" -e \"library('canadaHCD')\""  # [win]

about:
  home: https://github.com/gavinsimpson/canadaHCD
  license: GPL-3
  summary: Access climate data from Government of Canada's Historical
    Climate Data API.
  license_family: GPL3

extra:
  recipie-maintainers:
    - ConorIA
